/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.cookbook;

import com.sun.glass.events.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author kuba
 */
public class CookBookUI extends javax.swing.JFrame {

    /**
     *
     */
    static protected CookBookUI CB;
    private RecipeWindow RW;

    /**
     *
     */
    protected RecipeWindowSet RWS;

    /**
     *
     */
    protected DatabazeReceptu DB;

    /**
     *
     */
    protected Recept recept;
    private String hledej = "";

    /**
     * Creates new form CookBookUI
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws java.lang.ClassNotFoundException
     */
    public CookBookUI() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        DB = new DatabazeReceptu();
        DB.nactiNazvy(nazvyReceptuList);
        searchPanel.setVisible(false);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nazvyReceptuList = new java.awt.List();
        VytvorReceptBT = new javax.swing.JButton();
        vymazReceptBT = new javax.swing.JButton();
        najdiReceptBT = new javax.swing.JButton();
        searchPanel = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nazevReceptuTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        nazevIngTF1 = new javax.swing.JTextField();
        nazevIngTF2 = new javax.swing.JTextField();
        nazevIngTF3 = new javax.swing.JTextField();
        nazevIngTF4 = new javax.swing.JTextField();
        nazevIngTF5 = new javax.swing.JTextField();
        nazevIngTF6 = new javax.swing.JTextField();
        nazevIngTF7 = new javax.swing.JTextField();
        nazevIngTF8 = new javax.swing.JTextField();
        nazevIngTF9 = new javax.swing.JTextField();
        nazevIngTF10 = new javax.swing.JTextField();
        hledejBT = new javax.swing.JButton();
        ZobrazVsechnyBT = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recepty"));
        jPanel2.setPreferredSize(new java.awt.Dimension(403, 137));

        nazvyReceptuList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazvyReceptuListActionPerformed(evt);
            }
        });

        VytvorReceptBT.setText("Vytvoř recept");
        VytvorReceptBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VytvorReceptBTActionPerformed(evt);
            }
        });

        vymazReceptBT.setText("Vymaž recept");
        vymazReceptBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazReceptBTActionPerformed(evt);
            }
        });

        najdiReceptBT.setText("Najdi recept");
        najdiReceptBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                najdiReceptBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(nazvyReceptuList, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(VytvorReceptBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vymazReceptBT, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(najdiReceptBT))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {VytvorReceptBT, najdiReceptBT, vymazReceptBT});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(VytvorReceptBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(najdiReceptBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vymazReceptBT)
                .addContainerGap())
            .addComponent(nazvyReceptuList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {VytvorReceptBT, vymazReceptBT});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        searchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vyhledávání receptu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Název Receptu"));

        nazevReceptuTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevReceptuTFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nazevReceptuTF)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nazevReceptuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredience"));

        nazevIngTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF1KeyPressed(evt);
            }
        });

        nazevIngTF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF2KeyPressed(evt);
            }
        });

        nazevIngTF3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF3KeyPressed(evt);
            }
        });

        nazevIngTF4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF4KeyPressed(evt);
            }
        });

        nazevIngTF5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF5KeyPressed(evt);
            }
        });

        nazevIngTF6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF6KeyPressed(evt);
            }
        });

        nazevIngTF7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF7KeyPressed(evt);
            }
        });

        nazevIngTF8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF8KeyPressed(evt);
            }
        });

        nazevIngTF9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF9KeyPressed(evt);
            }
        });

        nazevIngTF10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazevIngTF10KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nazevIngTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nazevIngTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nazevIngTF1, nazevIngTF10, nazevIngTF2, nazevIngTF3, nazevIngTF4, nazevIngTF5, nazevIngTF6, nazevIngTF7, nazevIngTF8, nazevIngTF9});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nazevIngTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazevIngTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hledejBT.setText("Hledej");
        hledejBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hledejBTActionPerformed(evt);
            }
        });

        ZobrazVsechnyBT.setText("Zobraz všechy recepty");
        ZobrazVsechnyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZobrazVsechnyBTActionPerformed(evt);
            }
        });

        searchPanel.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchPanel.setLayer(hledejBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchPanel.setLayer(ZobrazVsechnyBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(hledejBT)
            .addComponent(ZobrazVsechnyBT)
        );

        searchPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ZobrazVsechnyBT, hledejBT, jPanel3});

        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hledejBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ZobrazVsechnyBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchPanel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VytvorReceptBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VytvorReceptBTActionPerformed
        try {
            RW = new RecipeWindow();
            RW.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(CookBookUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CookBookUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VytvorReceptBTActionPerformed

    private void nazvyReceptuListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazvyReceptuListActionPerformed
        recept = DB.nactiRecept(nazvyReceptuList.getSelectedItem());
        try {
            RWS = new RecipeWindowSet();
            RWS.setVisible(true);
            RWS.pack();
        } catch (IOException ex) {
            Logger.getLogger(CookBookUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CookBookUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nazvyReceptuListActionPerformed

    private void vymazReceptBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazReceptBTActionPerformed
        String[] nastaveni = {"smazat","zrušit"};
        int s = JOptionPane.showOptionDialog(this, "Opravdu chcete vymazat recept " + nazvyReceptuList.getSelectedItem() + "?",
            "",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE, null,
            nastaveni, nastaveni[1]);
        if (s == JOptionPane.OK_OPTION) {
            Recept r = DB.nactiRecept(nazvyReceptuList.getSelectedItem());
            DB.vymazRecept(r);
            DB.vymazReceptZeSlozky(r);
            DB.nactiNazvy(nazvyReceptuList);
        }
    }//GEN-LAST:event_vymazReceptBTActionPerformed

    private void najdiReceptBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_najdiReceptBTActionPerformed
        boolean visible = searchPanel.isVisible();
        searchPanel.setVisible(! visible);
        this.pack();
    }//GEN-LAST:event_najdiReceptBTActionPerformed
    private static String prevedText(String vstup) {
        return vstup = Normalizer.normalize(vstup, Normalizer.Form.NFKD).replaceAll("\\p{InCombiningDiacriticalMarks}+", "").replaceAll(" ", "").toLowerCase();        
    }
    private void hledejRecept() {
        ArrayList <String> nazvyIng = new ArrayList<>();
        if(!nazevIngTF1.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF1.getText()));}
        if(!nazevIngTF2.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF2.getText()));}
        if(!nazevIngTF3.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF3.getText()));}
        if(!nazevIngTF4.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF4.getText()));}
        if(!nazevIngTF5.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF5.getText()));}
        if(!nazevIngTF6.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF6.getText()));}
        if(!nazevIngTF7.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF7.getText()));}
        if(!nazevIngTF8.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF8.getText()));}
        if(!nazevIngTF9.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF9.getText()));}
        if(!nazevIngTF10.getText().isEmpty()) {nazvyIng.add(prevedText(nazevIngTF10.getText()));}             
        DB.hledejNazvyReceptu(nazvyReceptuList, nazevReceptuTF.getText(), nazvyIng);

    }
    private void hledejBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hledejBTActionPerformed
        this.hledejRecept();
    }//GEN-LAST:event_hledejBTActionPerformed

    private void ZobrazVsechnyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZobrazVsechnyBTActionPerformed
        DB.nactiNazvy(nazvyReceptuList);
    }//GEN-LAST:event_ZobrazVsechnyBTActionPerformed

    private void nazevIngTF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF1KeyPressed

    private void nazevIngTF2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF2KeyPressed

    private void nazevIngTF3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF3KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF3KeyPressed

    private void nazevIngTF4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF4KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF4KeyPressed

    private void nazevIngTF5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF5KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF5KeyPressed

    private void nazevIngTF6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF6KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF6KeyPressed

    private void nazevIngTF7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF7KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF7KeyPressed

    private void nazevIngTF8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF8KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF8KeyPressed

    private void nazevIngTF9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF9KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF9KeyPressed

    private void nazevIngTF10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevIngTF10KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevIngTF10KeyPressed

    private void nazevReceptuTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazevReceptuTFKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.hledejRecept();
        }
    }//GEN-LAST:event_nazevReceptuTFKeyPressed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        //Vytvoří hlavní složku pro recepty
        File hlavniSlozka = new File("Recepty//");
        boolean boolHlavniSlozka = hlavniSlozka.mkdir();
        if(boolHlavniSlozka) {
            System.out.println("Složka vytvořena.");
        }
        //Vytvoří složku s recepty
        File slozka = new File("Recepty//SerializedFiles//");
        boolean boolSlozka = slozka.mkdir();
        if(boolSlozka) {
            System.out.println("Složka vytvořena.");
        }
        //Vytvoří složku s obrázky 
        File obrazky = new File("Recepty//Obrazky");
        boolean boolObrazky = obrazky.mkdir();
        if(boolObrazky) {
            System.out.println("Složka vytvořena.");
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookBookUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookBookUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookBookUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookBookUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                CB = new CookBookUI();
                CB.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(CookBookUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CookBookUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VytvorReceptBT;
    private javax.swing.JButton ZobrazVsechnyBT;
    private javax.swing.JButton hledejBT;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton najdiReceptBT;
    private javax.swing.JTextField nazevIngTF1;
    private javax.swing.JTextField nazevIngTF10;
    private javax.swing.JTextField nazevIngTF2;
    private javax.swing.JTextField nazevIngTF3;
    private javax.swing.JTextField nazevIngTF4;
    private javax.swing.JTextField nazevIngTF5;
    private javax.swing.JTextField nazevIngTF6;
    private javax.swing.JTextField nazevIngTF7;
    private javax.swing.JTextField nazevIngTF8;
    private javax.swing.JTextField nazevIngTF9;
    private javax.swing.JTextField nazevReceptuTF;
    protected java.awt.List nazvyReceptuList;
    private javax.swing.JLayeredPane searchPanel;
    private javax.swing.JButton vymazReceptBT;
    // End of variables declaration//GEN-END:variables

}
