/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.cookbook;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author kuba
 */
public class RecipeWindow extends javax.swing.JFrame {
    private Recept recept = new Recept();
    private JFileChooser FC = new JFileChooser();;
    private String imgCesta = "";
    private Toolkit t = Toolkit.getDefaultToolkit();
    private Image img;
    private ImageIcon icon;
    private Obrazky obr = new Obrazky();

    /**
     * Creates new form RecipeWindow
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws java.lang.ClassNotFoundException
     */
    public RecipeWindow() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents(); 
        this.pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        popisReceptuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        popisReceptuTA = new javax.swing.JTextArea();
        pridejImgBT = new javax.swing.JButton();
        ulozBT = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        IngrediencePanel = new javax.swing.JPanel();
        nazevIngLabel = new javax.swing.JLabel();
        mnozstviIngLabel = new javax.swing.JLabel();
        nazevIngTF1 = new javax.swing.JTextField();
        nazevIngTF2 = new javax.swing.JTextField();
        nazevIngTF3 = new javax.swing.JTextField();
        nazevIngTF4 = new javax.swing.JTextField();
        nazevIngTF5 = new javax.swing.JTextField();
        nazevIngTF6 = new javax.swing.JTextField();
        nazevIngTF7 = new javax.swing.JTextField();
        nazevIngTF8 = new javax.swing.JTextField();
        nazevIngTF9 = new javax.swing.JTextField();
        nazevIngTF10 = new javax.swing.JTextField();
        mnozstviIngTF1 = new javax.swing.JTextField();
        mnozstviIngTF2 = new javax.swing.JTextField();
        mnozstviIngTF3 = new javax.swing.JTextField();
        mnozstviIngTF4 = new javax.swing.JTextField();
        mnozstviIngTF5 = new javax.swing.JTextField();
        mnozstviIngTF6 = new javax.swing.JTextField();
        mnozstviIngTF7 = new javax.swing.JTextField();
        mnozstviIngTF8 = new javax.swing.JTextField();
        mnozstviIngTF9 = new javax.swing.JTextField();
        mnozstviIngTF10 = new javax.swing.JTextField();
        nazevIngTF11 = new javax.swing.JTextField();
        mnozstviIngTF11 = new javax.swing.JTextField();
        mnozstviIngTF12 = new javax.swing.JTextField();
        mnozstviIngTF13 = new javax.swing.JTextField();
        mnozstviIngTF14 = new javax.swing.JTextField();
        mnozstviIngTF15 = new javax.swing.JTextField();
        mnozstviIngTF16 = new javax.swing.JTextField();
        mnozstviIngTF17 = new javax.swing.JTextField();
        mnozstviIngTF18 = new javax.swing.JTextField();
        mnozstviIngTF19 = new javax.swing.JTextField();
        mnozstviIngTF20 = new javax.swing.JTextField();
        nazevIngTF12 = new javax.swing.JTextField();
        nazevIngTF13 = new javax.swing.JTextField();
        nazevIngTF14 = new javax.swing.JTextField();
        nazevIngTF15 = new javax.swing.JTextField();
        nazevIngTF16 = new javax.swing.JTextField();
        nazevIngTF17 = new javax.swing.JTextField();
        nazevIngTF18 = new javax.swing.JTextField();
        nazevIngTF19 = new javax.swing.JTextField();
        nazevIngTF20 = new javax.swing.JTextField();
        nazevReceptuPanel = new javax.swing.JPanel();
        nazevReceptuTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vytvoření receptu");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        popisReceptuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Popis receptu"));

        popisReceptuTA.setColumns(20);
        popisReceptuTA.setRows(5);
        jScrollPane1.setViewportView(popisReceptuTA);

        pridejImgBT.setText("Přidej obrázek");
        pridejImgBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridejImgBTActionPerformed(evt);
            }
        });

        ulozBT.setText("Ulož");
        ulozBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulozBTActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imgLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout popisReceptuPanelLayout = new javax.swing.GroupLayout(popisReceptuPanel);
        popisReceptuPanel.setLayout(popisReceptuPanelLayout);
        popisReceptuPanelLayout.setHorizontalGroup(
            popisReceptuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popisReceptuPanelLayout.createSequentialGroup()
                .addComponent(pridejImgBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(ulozBT, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        popisReceptuPanelLayout.setVerticalGroup(
            popisReceptuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popisReceptuPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(popisReceptuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridejImgBT)
                    .addComponent(ulozBT)))
        );

        IngrediencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredience"));

        nazevIngLabel.setText("Název");

        mnozstviIngLabel.setText("Množství");

        javax.swing.GroupLayout IngrediencePanelLayout = new javax.swing.GroupLayout(IngrediencePanel);
        IngrediencePanel.setLayout(IngrediencePanelLayout);
        IngrediencePanelLayout.setHorizontalGroup(
            IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngrediencePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(nazevIngLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mnozstviIngLabel)
                .addGap(26, 26, 26))
            .addGroup(IngrediencePanelLayout.createSequentialGroup()
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addComponent(nazevIngTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnozstviIngTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngrediencePanelLayout.createSequentialGroup()
                        .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nazevIngTF10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(nazevIngTF9))
                            .addComponent(nazevIngTF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazevIngTF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mnozstviIngTF10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(mnozstviIngTF9)
                            .addComponent(mnozstviIngTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnozstviIngTF11))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        IngrediencePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mnozstviIngTF1, mnozstviIngTF10, mnozstviIngTF11, mnozstviIngTF12, mnozstviIngTF13, mnozstviIngTF14, mnozstviIngTF15, mnozstviIngTF16, mnozstviIngTF17, mnozstviIngTF18, mnozstviIngTF19, mnozstviIngTF2, mnozstviIngTF20, mnozstviIngTF3, mnozstviIngTF4, mnozstviIngTF5, mnozstviIngTF6, mnozstviIngTF7, mnozstviIngTF8, mnozstviIngTF9, nazevIngTF1, nazevIngTF10, nazevIngTF11, nazevIngTF12, nazevIngTF13, nazevIngTF14, nazevIngTF15, nazevIngTF16, nazevIngTF17, nazevIngTF18, nazevIngTF19, nazevIngTF2, nazevIngTF20, nazevIngTF3, nazevIngTF4, nazevIngTF5, nazevIngTF6, nazevIngTF7, nazevIngTF8, nazevIngTF9});

        IngrediencePanelLayout.setVerticalGroup(
            IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngrediencePanelLayout.createSequentialGroup()
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngLabel)
                    .addComponent(mnozstviIngLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mnozstviIngTF1)
                    .addComponent(nazevIngTF1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazevIngTF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnozstviIngTF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngrediencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnozstviIngTF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazevIngTF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IngrediencePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mnozstviIngTF1, mnozstviIngTF10, mnozstviIngTF2, mnozstviIngTF3, mnozstviIngTF4, mnozstviIngTF5, mnozstviIngTF6, mnozstviIngTF7, mnozstviIngTF8, mnozstviIngTF9, nazevIngTF10, nazevIngTF2, nazevIngTF3, nazevIngTF4, nazevIngTF5, nazevIngTF6, nazevIngTF7, nazevIngTF8, nazevIngTF9});

        nazevReceptuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Název receptu"));

        javax.swing.GroupLayout nazevReceptuPanelLayout = new javax.swing.GroupLayout(nazevReceptuPanel);
        nazevReceptuPanel.setLayout(nazevReceptuPanelLayout);
        nazevReceptuPanelLayout.setHorizontalGroup(
            nazevReceptuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nazevReceptuTF)
        );
        nazevReceptuPanelLayout.setVerticalGroup(
            nazevReceptuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nazevReceptuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(popisReceptuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nazevReceptuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngrediencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nazevReceptuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(popisReceptuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(IngrediencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ulozBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulozBTActionPerformed

        if(!CookBookUI.CB.DB.receptExists(nazevReceptuTF.getText())) {
            if(!nazevReceptuTF.getText().equals("")) {
                recept.setNazev(nazevReceptuTF.getText());
                recept.setPopis(popisReceptuTA.getText());
                recept.setIngredience(nazevIngTF1.getText(), mnozstviIngTF1.getText());
                recept.setIngredience(nazevIngTF2.getText(), mnozstviIngTF2.getText());
                recept.setIngredience(nazevIngTF3.getText(), mnozstviIngTF3.getText());
                recept.setIngredience(nazevIngTF4.getText(), mnozstviIngTF4.getText());
                recept.setIngredience(nazevIngTF5.getText(), mnozstviIngTF5.getText());
                recept.setIngredience(nazevIngTF6.getText(), mnozstviIngTF6.getText());
                recept.setIngredience(nazevIngTF7.getText(), mnozstviIngTF7.getText());
                recept.setIngredience(nazevIngTF8.getText(), mnozstviIngTF8.getText());
                recept.setIngredience(nazevIngTF9.getText(), mnozstviIngTF9.getText());
                recept.setIngredience(nazevIngTF10.getText(), mnozstviIngTF10.getText());
                recept.setIngredience(nazevIngTF11.getText(), mnozstviIngTF11.getText());
                recept.setIngredience(nazevIngTF12.getText(), mnozstviIngTF12.getText());
                recept.setIngredience(nazevIngTF13.getText(), mnozstviIngTF13.getText());
                recept.setIngredience(nazevIngTF14.getText(), mnozstviIngTF14.getText());
                recept.setIngredience(nazevIngTF15.getText(), mnozstviIngTF15.getText());
                recept.setIngredience(nazevIngTF16.getText(), mnozstviIngTF16.getText());
                recept.setIngredience(nazevIngTF17.getText(), mnozstviIngTF17.getText());
                recept.setIngredience(nazevIngTF18.getText(), mnozstviIngTF18.getText());
                recept.setIngredience(nazevIngTF19.getText(), mnozstviIngTF19.getText());
                recept.setIngredience(nazevIngTF20.getText(), mnozstviIngTF20.getText());
                try {
                    obr.ulozObrazek(imgCesta, nazevReceptuTF.getText());
                } catch (IOException ex) {
                    Logger.getLogger(RecipeWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                CookBookUI.CB.DB.ulozRecept(recept);
                //System.out.println(CookBookUI.CB.DB.testUlozeni());
            }                   
            CookBookUI.CB.DB.nactiNazvy(CookBookUI.CB.nazvyReceptuList);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Recept s názvem " + nazevReceptuTF.getText() + " již existuje.");
        }
    }//GEN-LAST:event_ulozBTActionPerformed

    private void pridejImgBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridejImgBTActionPerformed
        if(evt.getSource() == pridejImgBT) {
            int returnVal = FC.showOpenDialog(jPanel1);
            if(returnVal == JFileChooser.APPROVE_OPTION) {
                imgCesta = FC.getSelectedFile().getAbsolutePath();
                System.out.println(imgCesta); //test
            }
        }
        img = t.getImage(imgCesta);
        icon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), Image.SCALE_DEFAULT));
        imgLabel.setIcon(icon);
        
    }//GEN-LAST:event_pridejImgBTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> {
            new RecipeWindow().setVisible(true);
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IngrediencePanel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mnozstviIngLabel;
    private javax.swing.JTextField mnozstviIngTF1;
    private javax.swing.JTextField mnozstviIngTF10;
    private javax.swing.JTextField mnozstviIngTF11;
    private javax.swing.JTextField mnozstviIngTF12;
    private javax.swing.JTextField mnozstviIngTF13;
    private javax.swing.JTextField mnozstviIngTF14;
    private javax.swing.JTextField mnozstviIngTF15;
    private javax.swing.JTextField mnozstviIngTF16;
    private javax.swing.JTextField mnozstviIngTF17;
    private javax.swing.JTextField mnozstviIngTF18;
    private javax.swing.JTextField mnozstviIngTF19;
    private javax.swing.JTextField mnozstviIngTF2;
    private javax.swing.JTextField mnozstviIngTF20;
    private javax.swing.JTextField mnozstviIngTF3;
    private javax.swing.JTextField mnozstviIngTF4;
    private javax.swing.JTextField mnozstviIngTF5;
    private javax.swing.JTextField mnozstviIngTF6;
    private javax.swing.JTextField mnozstviIngTF7;
    private javax.swing.JTextField mnozstviIngTF8;
    private javax.swing.JTextField mnozstviIngTF9;
    private javax.swing.JLabel nazevIngLabel;
    private javax.swing.JTextField nazevIngTF1;
    private javax.swing.JTextField nazevIngTF10;
    private javax.swing.JTextField nazevIngTF11;
    private javax.swing.JTextField nazevIngTF12;
    private javax.swing.JTextField nazevIngTF13;
    private javax.swing.JTextField nazevIngTF14;
    private javax.swing.JTextField nazevIngTF15;
    private javax.swing.JTextField nazevIngTF16;
    private javax.swing.JTextField nazevIngTF17;
    private javax.swing.JTextField nazevIngTF18;
    private javax.swing.JTextField nazevIngTF19;
    private javax.swing.JTextField nazevIngTF2;
    private javax.swing.JTextField nazevIngTF20;
    private javax.swing.JTextField nazevIngTF3;
    private javax.swing.JTextField nazevIngTF4;
    private javax.swing.JTextField nazevIngTF5;
    private javax.swing.JTextField nazevIngTF6;
    private javax.swing.JTextField nazevIngTF7;
    private javax.swing.JTextField nazevIngTF8;
    private javax.swing.JTextField nazevIngTF9;
    private javax.swing.JPanel nazevReceptuPanel;
    private javax.swing.JTextField nazevReceptuTF;
    private javax.swing.JPanel popisReceptuPanel;
    private javax.swing.JTextArea popisReceptuTA;
    private javax.swing.JButton pridejImgBT;
    private javax.swing.JToggleButton ulozBT;
    // End of variables declaration//GEN-END:variables
}
